### ISSUE TITLE
Need to add documentation on how to run the static site after making a change to the devdocs 

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-devdoc#45]
After doing a _bundle exec jekyll build_ , the developer must check if the changes look good in the website HTML page(s).

To do this:
Put the _site directory contents inside an apache server directory and access it on the browser. This might be trivial but adding it here to help come up with an automated task ( maybe containerised ? ) to run the website via a command after doing the build.

Personally, I executed 
`python -m SimpleHTTPServer 8111` inside the _site directory and could access the website at 
http://localhost:8111

Created this issue to ensure that sometime in the near future we need to 
- develop a simpler way to run the website after the build.
- document this somewhere.

**Comment by aslakknutsen** [comment]
Jekyll serve?

**Comment by sbose78** [comment]
Thanks @aslakknutsen .
That works! ( Wasn't aware :) ) 

Will add that to the documentation.

**Comment by sbose78** [comment]
Opened a PR for the same. https://github.com/almighty/almighty-devdoc/pull/46 @aslakknutsen
