### ISSUE TITLE
Add tutorial on how to download / use Almighty?

### ISSUE THREAD

**Issue by cdrage** [fabric8-services/fabric8-devdoc#66]
Might be too early to add, but perhaps adding some installation instructions / for development on how to get started with Almighty (from a UI perspective)?

As a new user (just going through the docs and all now) the only source of building is the `docker-compose.yml` in https://github.com/almighty/almighty-ui

**Comment by sbose78** [comment]
Hi @cdrage 
Are you proprosing a almighty-ui developer guide?

**Comment by cdrage** [comment]
@sbose78 Nope, just using / setting up Almighty!
