### ISSUE TITLE
almighty-devdoc unusable on mobile

### ISSUE THREAD

**Issue by AdamJ** [fabric8-services/fabric8-devdoc#83]
when viewing almighty-devdoc.io on mobile, the site is unusable.

![screen shot 2016-10-04 at 12 31 13 pm](https://cloud.githubusercontent.com/assets/4032718/19083057/a95a2d10-8a2e-11e6-90c5-116e29099f5c.png)

**Comment by bartoszmajsak** [comment]
Works on my machine

![image](https://cloud.githubusercontent.com/assets/719616/19083558/ece45f72-8a62-11e6-9c55-d4178bc13eca.png)

Chrome 53.0.2785.124
Android 6.0.1

**Comment by AdamJ** [comment]
@bartoszmajsak - the table on the home page does not scale down to mobile. Not knowing how the site is actually rendering everything, this may/may not become an issue if/when additional tables are added to the site.
