### ISSUE TITLE
Images Don't Appear on devdoc.almighty.io

### ISSUE THREAD

**Issue by AdamJ** [fabric8-services/fabric8-devdoc#98]
Images that appear inside of GitHub do not appear on the site. The path is written correctly, in the code, but there seems to be a disconnect between the repo and the generated site.

**GitHub Repo:**
<img width="1030" alt="screen shot 2016-10-26 at 10 53 06 am" src="https://cloud.githubusercontent.com/assets/4032718/19731123/6ca0d124-9b6a-11e6-9ba0-74c04e4dba29.png">

**devdoc.almighty.io:**
<img width="946" alt="screen shot 2016-10-26 at 10 52 52 am" src="https://cloud.githubusercontent.com/assets/4032718/19731131/736541b6-9b6a-11e6-884b-9e7e0e3b2d7b.png">

**Comment by maxandersen** [comment]
so something is definitely of - for some reason `/images` is force added on any image url meaning you can't have it render nice on github and on the site. 

must be a bad jekyll flag somewhere.
